# Generated by Django 5.0.1 on 2024-02-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenantAwareModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subdomain", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "tenantawaremodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multi_tenant.tenantawaremodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("bio", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=("multi_tenant.tenantawaremodel",),
        ),
        migrations.AddField(
            model_name="tenantawaremodel",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="multi_tenant.tenant"
            ),
        ),
    ]
